// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlS5SAy4Ji6YzeBaiyQLZ3qtnGS-J4Zkc',
    appId: '1:905515768658:web:a4d7c384896414b4f6b88b',
    messagingSenderId: '905515768658',
    projectId: 'authtutorial-1a05a',
    authDomain: 'authtutorial-1a05a.firebaseapp.com',
    storageBucket: 'authtutorial-1a05a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbxXfdKkfdP5mzGfjD_jwHGMSl98gAwh8',
    appId: '1:905515768658:android:d858ebacdda693b4f6b88b',
    messagingSenderId: '905515768658',
    projectId: 'authtutorial-1a05a',
    storageBucket: 'authtutorial-1a05a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDORzPZVSG4cFCCC0dRhUwAMDEwIsJQzrM',
    appId: '1:905515768658:ios:55144dd04e967aa6f6b88b',
    messagingSenderId: '905515768658',
    projectId: 'authtutorial-1a05a',
    storageBucket: 'authtutorial-1a05a.appspot.com',
    iosClientId: '905515768658-c18tb5p0clnkvor727h2kir05ut464ik.apps.googleusercontent.com',
    iosBundleId: 'com.example.love',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDORzPZVSG4cFCCC0dRhUwAMDEwIsJQzrM',
    appId: '1:905515768658:ios:55144dd04e967aa6f6b88b',
    messagingSenderId: '905515768658',
    projectId: 'authtutorial-1a05a',
    storageBucket: 'authtutorial-1a05a.appspot.com',
    iosClientId: '905515768658-c18tb5p0clnkvor727h2kir05ut464ik.apps.googleusercontent.com',
    iosBundleId: 'com.example.love',
  );
}
